import Head from "next/head";
import Image from "next/image";
import { themeClass, exampleStyle } from "./index.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={themeClass}>
        <h1 className={exampleStyle}>Hello world!</h1>
      </section>

    </div>
  );
}
