import Head from "next/head";
import { exampleStyle, container } from "./index.css";
import { themeA, themeB } from '../styles/theme.css'

export default function Home() {
  return (
    <div className={themeA}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={container}>
        <section>
          <h1 className={exampleStyle}>Hello world!</h1>
        </section>
      </div>
    </div>
  );
}
