import Head from "next/head";
import { exampleStyle, container } from "./index.css";
import { themeA, themeB } from "../styles/theme.css";
import { useState } from "react";

export default function Home() {
  const [whitelabel, setWhiteLabel] = useState("matcha");
  const theme = whitelabel === "matcha" ? themeA : themeB;
  return (
    <div className={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="checkbox"
        onChange={(e) => {
          e.target.checked ? setWhiteLabel("matcha") : setWhiteLabel("uniswap");
        }}
      />

      <div className={container}>
        <section>
          <p className={exampleStyle}>{whitelabel}</p>
        </section>
      </div>
    </div>
  );
}
